name: Android Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: checkout submodule
        run: git submodule sync --recursive && git submodule update --init --recursive

      - name: build
        uses: xdtianyu/actions-android-ci@master
        with:
          args: '"
        source /opt/setup-android-sdk.sh;
        ./gradlew assembleDebug
        "'

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: sample
          path: sample/build/outputs/apk/debug